config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  devise_for :users
  root 'home#index'
  resources :journals do
    resources :posts
  end
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/journal.rb
class Journal < ApplicationRecord
  has_many :posts
  belongs_to :user
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all.where(user_id: current_user.id)
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:title, :string, :user_id)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_with(model: journal, local: true) do |form| %>
  <% if journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
        <% journal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<div class="container">
<% if @journals.size == 0 %> 
<h2>Welcome, <%= current_user.name %>.</h2><br/>
<p> We're so glad you could make it. To get started, let's
  <%= link_to 'create your journal', new_journal_path %> 
  so you have somewhere to start posting!</p> 
<% else %>
<h2> Welcome back, <%= current_user.name %></h2>
  <% @journals.each do |journal| %>
  <div class="container">
      <h3><%= journal.title %></h3>
      <p><%= link_to 'Edit Journal Title', edit_journal_path(journal) %> || 
      <%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %></p>

      <% if journal.posts.count != 0 %>
        <%= render 'shared/post_cards' %>
      <% else %>
        <p><strong> It looks like you haven't written any entries yet! </strong></p>
        <%= link_to 'New post', new_journal_post_path(journal), :class => 'btn btn-primary text-light' %>
      <% end %>
      <br/>
    </div>
  <% end %>

  <br>
<% end %>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
 <div class="container">
      <h3><%= @journal.title %></h3>
      <p><%= link_to 'Edit Journal Title', edit_journal_path(@journal) %> || 
      <%= link_to 'Destroy', @journal, method: :delete, data: { confirm: 'Are you sure?' } %></p>

      <% if @journal.posts.count != 0 %>
        <%= render 'shared/post_cards' %>
        <% end %>
      <% else %>
        <p><strong> It looks like you haven't written any entries yet! </strong></p>
      <% end %>
      <%= link_to 'New post', new_journal_post_path(@journal), :class => 'btn'%>
    </div>


  <br>