config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  devise_for :users
  root 'home#index'
  resources :journals do
    resources :posts
  end
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :journal

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.where(journal_id: current_user.journal.id).paginate(page: params[:page], per_page: 6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:journal_id, :title, :rating, :content, :keywords)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :journal_id, value: current_user.journal.id %>

  <div class="field">
    <%= form.label :title %>
    <br/>
    <%= form.text_field :title %>
  </div>

  <div class="field rating">
    <%= form.label :rating, "How would you rate your day?" %>
    <br/>
    <table>
      <thead>
        <tr class="rating-headings">
          <th><%= form.label :rating, '1', value: '1' %></th>
          <th><%= form.label :rating, '2', value: '2' %></th>
          <th><%= form.label :rating, '3', value: '3' %></th>
          <th><%= form.label :rating, '4', value: '4' %></th>
          <th><%= form.label :rating, '5', value: '5' %></th>
        </tr>
      </thead>
    
      <tbody>
        <tr>
          <td><%= form.radio_button :rating, '1' %></td>
          <td><%= form.radio_button :rating, '2' %></td>
          <td><%= form.radio_button :rating, '3' %></td>
          <td><%= form.radio_button :rating, '4' %></td>
          <td><%= form.radio_button :rating, '5' %></td>
        </tr>
      </tbody>
    </table>

    
  </div>

  <div class="field">
    <%= form.label :content %>
    <br/>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :keywords %>
    <em>(if multiple, seperate with commas, ie "work, school")</em>
    <br/>
    <%= form.text_field :keywords %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<br/>

<%= render 'shared/post_cards'%>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title"><%= @post.title %></h2>
      <%= @post.created_at %> || Rating: <%= @post.rating %>
    </div>
    <div class="card-body">
      <p class="card-text">
        <%= @post.content %>
      </p>
      <p>
        <strong>Keywords:</strong> <em><%= @post.keywords %></em>
      </p>
      <p>
        <%= link_to 'Edit', edit_post_path(@post), :class => 'card-link'%> 
        <%= link_to 'Back', journal_posts_path(@post.journal_id), :class => 'card-link '%>
      </p>
    </div>
  </div>
</div>